### PR TITLE
Release 0.0.34.

### PR DESCRIPTION
**Pull request by cfallin**
New release in order to include #139.

### CODE REVIEW

**Review by fitzgen — APPROVED** [review]

**Comment by fitzgen** [comment]
Looks like my approval isn't enough to unblock this PR.

**Comment by cfallin** [comment]
Hmm, seems that I don't have admin access to change that setting or to add you as a collaborator either. @tschneidereit or someone else with BA admin, could you apply the usual "cranelift-core has full access" permissions here?

**Comment by tschneidereit** [comment]
@cfallin done!

**Comment by cfallin** [comment]
@fitzgen v0.0.34 pushed to crates.io!

**Pull request merged**
